coding best practices
msarath95/mle-training pull request #3
Opened 2020-09-22 04:20 UTC by msarath95

This PR contains:

- README.md  document on how to install/run your code
- An env.yaml which is the conda environment 
- A script to train and score the model
- A script to score a pre-trained (from previous step) model(s)
- A script to make a prediction using your trained model
- Packaged and installable
- unit-tests to test the imputer
- documentation

The following are the things to do

- Ensure that your scripts generate a log for every run
- Improve the test cases

2020-09-29 08:42 UTC, senganal-ta requested changes
Overall looks quite good.. Added some comments, pls. request a review after fixing them..

Also, please add support for logging.

2020-09-29 08:42 UTC, senganal-ta commented on tests/tests_housing.py
> +        finally:
try/finally block is redundant.

2020-09-29 08:42 UTC, senganal-ta commented on tests/tests_housing.py
> +from __future__ import print_function
not needed.. we are on py3.

2020-09-29 08:42 UTC, senganal-ta commented on notebook/eda.py
> +corr_matrix["median_house_value"].sort_values(ascending=False)
i guess the intention for these snippets is to be loaded into a notebook or ipython interpreter ?

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/modeling/eval.py
> +    :rtype: float
not the numpy docstring style

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/modeling/eval.py
> +        raise Exception("y_true & y_hat should be of equal length")
generally good to raise a `ValueError`  when the inputs are problematic. .same for the function above. and elsewhere

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/modeling/score.py
> +from housing.preparation import data_utils as du
two letter abbrevs are useful when exploring on an interpreter.. less so in a production script. `data_utils` is more readable and concise enough..

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/modeling/score.py
> +    model = pkl.load(open(cfg["models_path"] + "/model_{version}.pkl".format(**cfg), "rb"))
use os.path or pathlib for file path manipulations.

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/preparation/data_utils.py
> +    return data_exists
here `os.path.exists` does the same job as the function.. not much value in creating a function for this unless you also plan to support urls (e.g. s3 urls) and/or other paths in addition to local filesystem paths..

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/preparation/data_utils.py
> +    create_data = not is_data_exists(housing_path) or over_write_raw_data
for complex boolean condition, its more readable to use paranthesis to group expressions
```
create_data = ((not is_data_exists())
               or (over_write_raw_data))
```

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/preparation/data_utils.py
> +    """This function is used to download the data
Add a fullstop at the end of the sentence.

2020-09-29 08:42 UTC, senganal-ta commented on src/housing/preparation/data_utils.py
> +        pkl.dump(imputer, open(cfg["models_path"] + "/imputer_{version}.pkl".format(**cfg), "wb"))
use `os.path` for path manipulations

2020-09-29 08:42 UTC, senganal-ta commented on tests/tests_housing.py
> +            "x{}".format(x) for x in range(5)])
inconsistent style.. pls. run the formatter

2020-10-05 06:54 UTC, msarath95 commented on tests/tests_housing.py
> +        finally:
Did you mean we have to change it to `expect` instead of `finally`?

2020-10-05 06:55 UTC, msarath95 commented on notebook/eda.py
> +corr_matrix["median_house_value"].sort_values(ascending=False)
Yes, these code snippets are to be executed in the python interpreter or in notebook

2020-10-05 06:59 UTC, msarath95 commented on src/housing/preparation/data_utils.py
> +    return data_exists
Noted, for now, I'm keeping it as a function, in future we can add s3 support if required

2020-10-06 02:56 UTC, senganal-ta requested changes
one minor comment.. pls. fix that.. 

I saw the logger being configured but not being used in the train/score functions.. It would be good to log some more useful information..

Pls. feel free to merge after addressing the above comments..

2020-10-06 02:56 UTC, senganal-ta commented on src/housing/preparation/utils.py
> +    logging.config.fileConfig(fname='./config/log.conf')
you prob. meant to use `log_conf` instead of the hardcoded path to config file..

2020-10-06 02:56 UTC, senganal-ta commented on src/housing/processing/processing.py
> +logger = logging.getLogger()
`logging.getLogger(__name__)` would ensure that the module name is included as part of the log msg. useful for debugging.

2020-10-08 05:33 UTC, senganal-ta commented
LGTM. Pls. feel free to merge.. Once merged, pls. update #4 with a master merge so that only the new changes are shown in the diff..

2020-10-08 05:33 UTC, senganal-ta approved these changes

2020-10-08 05:39 UTC, merged